In [ ]:
import numpy as np

In [ ]:
l1 = [1,2,3,4]

In [ ]:
array1 = np.array(l1)

In [ ]:
#all elements in array must be same data type
array1

array([1, 2, 3, 4])

In [ ]:
l2 = [11,22,33,44]

In [ ]:
l = [l1,l2]
l

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [ ]:
array_2D = np.array(l)
array_2D

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [ ]:
array_2D.shape

(2, 4)

In [ ]:
array_2D.dtype

dtype('int64')

In [ ]:
np.zeros(3, 'int')

array([0, 0, 0])

In [ ]:
np.zeros([3,3],"int")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros([4,3,2],"int")

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [ ]:
np.ones([3,2,4],"int")

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
np.empty(4)

array([1.33076952e-315, 0.00000000e+000, 5.91842491e-085, 1.24002374e+180])

In [ ]:
np.empty([2,1,3],"int")

array([[[          268878601,                   0, 6061971993792638575]],

       [[2314861247312786802, 7800551649446141984,         42950356851]]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [ ]:
arr1= np.array([[1,2,3,4],[8,9,10,11]])
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [ ]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [ ]:
arr1*2

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

In [ ]:
arr1 + 1

array([[ 2,  3,  4,  5],
       [ 9, 10, 11, 12]])

In [ ]:
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

In [ ]:
arr1.T

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11]])

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
print(A)
print('\n')

B = np.array([[7,8],[9,10],[11,12]])
print(B)
print('\n')

np.dot(A,B)

[[1 2 3]
 [4 5 6]]


[[ 7  8]
 [ 9 10]
 [11 12]]




array([[ 58,  64],
       [139, 154]])

In [ ]:
a1 = [1,3,5]
ar1 = np.array(a1)

a2 = [2,4,6]
ar2 = np.array(a2)

add = ar1 + ar2
print(add)

sub = ar1 - ar2
print(sub)

multiply = ar1 * ar2
print(multiply)

divide = ar1 / ar2
print(divide)



[ 3  7 11]
[-1 -1 -1]
[ 2 12 30]
[0.5        0.75       0.83333333]


In [ ]:
arr= np.arange(0,11)

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
slice = arr[0:5]
slice

array([100, 100, 100, 100, 100])

In [ ]:
slice[:] = 99
slice

array([99, 99, 99, 99, 99])

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#slicing [ : ]
#indexing [rows , columns]

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[: , 1]

array([2, 5, 8])

In [ ]:
#row index 1 , column index 2
print(A[1][2])

6


In [ ]:
#slicing inside indexing  :3 --> row , 1: --> column
A[:3, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
A[:1, 2:]

array([[3]])

In [ ]:
A[:3, ::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [ ]:
A[:3, 2::]

array([[3],
       [6],
       [9]])

In [ ]:
grid = np.arange(1,13).reshape((3,4))
grid

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
grid = np.arange(1,13).reshape((2,6))
grid

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
np.concatenate([grid,grid]) # by defauly axis = 0 , add number of rows

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
np.concatenate([grid,grid],axis = 1) # axis = 1 , add number of columns

array([[ 1,  2,  3,  4,  5,  6,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12,  7,  8,  9, 10, 11, 12]])

In [ ]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x, [3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [ ]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x, [2,6])
print(x1,x2,x3)

[1 2] [ 3 99 99  3] [2 1]


In [ ]:
#vsplit --> split by rows
grid = np.arange(16).reshape((4, 4))
print(grid)
print("\n")
upper, lower = np.vsplit(grid, [2])
print(upper)
print("\n")
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[0 1 2 3]
 [4 5 6 7]]


[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
#hsplit --> split by columns
grid = np.arange(16).reshape((4, 4))
print(grid)
print("\n")
left, right = np.hsplit(grid, [3])
print(left)
print("\n")
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


[[ 3]
 [ 7]
 [11]
 [15]]


In [ ]:
grades = [
    [78, 45, 32],
    [55, 88, 25],
    [90, 35, 70]
]

print("Average grade of each student:")
for i in range(len(grades)):
    avg = sum(grades[i]) / len(grades[i])
    print(f"Student {i+1}: {avg}")

subjects = ["Math", "Science", "English"]
print("\nHighest grade in each subject:")
for j in range(3):
    highest = max(grades[i][j] for i in range(len(grades)))
    print(f"{subjects[j]}: {highest}")

total = sum(sum(student) for student in grades)
count = len(grades) * 3
overallAverage = total / count
print(f"\nOverall average grade: {overallAverage}")


Average grade of each student:
Student 1: 51.666666666666664
Student 2: 56.0
Student 3: 65.0

Highest grade in each subject:
Math: 90
Science: 88
English: 70

Overall average grade: 57.55555555555556


In [ ]:
from statistics import mean

grades = [
    [78, 45, 32],
    [55, 88, 25],
    [90, 35, 70]
]

subjects = ["Math", "Science", "English"]

# Average grade of each student
print("Average grade of each student:")
print(f"Student 1: {mean(grades[0])}")
print(f"Student 2: {mean(grades[1])}")
print(f"Student 3: {mean(grades[2])}")

# Highest grade in each subject
print("\nHighest grade in each subject:")
print(f"{subjects[0]}: {max(grades[0][0], grades[1][0], grades[2][0])}")
print(f"{subjects[1]}: {max(grades[0][1], grades[1][1], grades[2][1])}")
print(f"{subjects[2]}: {max(grades[0][2], grades[1][2], grades[2][2])}")

# Overall average grade
all_grades = grades[0] + grades[1] + grades[2]
print(f"\nOverall average grade: {mean(all_grades)}")


Average grade of each student:
Student 1: 51.666666666666664
Student 2: 56
Student 3: 65

Highest grade in each subject:
Math: 90
Science: 88
English: 70

Overall average grade: 57.55555555555556


In [ ]:
import numpy as np
grades = np.array([
    [78, 45, 32],
    [55, 88, 25],
    [90, 35, 70]
])

studentMean = np.mean(grades, axis = 1)
print(studentMean)

heighGrade = np.max(grades, axis = 0)
print(heighGrade)


allGrades = np.mean(grades)
print(allGrades)

[51.66666667 56.         65.        ]
[90 88 70]
57.55555555555556


In [ ]:
A = np.array([1,2,3,4])
B = np.array([100,200,300,400])

condition = np.array([True,True,False,False])

answer2 = np.where(condition, A, B)
answer2

array([  1,   2, 300, 400])

In [ ]:
from numpy.random import randn
from numpy.random import randint

In [ ]:
arr = randn(2,2)
arr

array([[-0.87650254,  0.60024781],
       [-0.57345334, -0.07355707]])

In [ ]:
#random number between 1 and 20
a1 = randint(1,20)
a1

3

In [ ]:
np.where(arr < 0,6,arr)


array([[6.        , 0.60024781],
       [6.        , 6.        ]])

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(arr1.sum())

45


In [ ]:
#sum over rows
print(arr1.sum(1))

[ 6 15 24]


In [ ]:
#sum over columns
print(arr1.sum(0))

[12 15 18]


In [ ]:
#Mean
print(arr1.mean())

5.0


In [ ]:
#standard deviation
print(arr1.std())

2.581988897471611


In [ ]:
#variance
print(arr1.var())

6.666666666666667


In [ ]:
A=np.array([-2,5,4,-8,0])
print(A)

[-2  5  4 -8  0]


In [ ]:
print(np.sort(A)) #Ascending
print(- np.sort(-A)) #Descending

[-8 -2  0  4  5]
[ 5  4  0 -2 -8]


In [ ]:
countries = np.array(['France', 'Germany', 'USA','Russia','USA','Mexico',
                      'Germany','France', 'Germany', 'USA','Russia',
                      'USA','Mexico','Germany','France', 'Germany',
                      'USA','Russia','USA','Mexico','Germany','France',
                      'Germany','USA','Russia','USA','Mexico','Germany'])
print(np.unique(countries))

['France' 'Germany' 'Mexico' 'Russia' 'USA']


In [ ]:
np.in1d(['USA', 'Oman', 'Dubai'],countries)

<ipython-input-40-ec5f0843066c>:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(['USA', 'Oman', 'Dubai'],countries)


array([ True, False, False])